[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = "Backend of ShareYourCloning, a web application to generate molecular cloning strategies in json format, and share them with others."
license = "MIT"
name = "shareyourcloning_backend"
version = "0.1.0"

[tool.poetry.dependencies]
beautifulsoup4 = "^4.11.1"
biopython = "*"
dna_functions = {path = "./dna_functions", develop = true}
fastapi = "*"
pydna = {git = "https://github.com/manulera/pydna", develop = true}
python = "^3.9"
python-multipart = "*"
uvicorn = "*"

[tool.poetry.dev-dependencies]
autopep8 = "*"
flake8 = "*"
ipykernel = "*"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
